version: "3.1"

services: 

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "cours:/var/lib/redis/data"
    entrypoint: redis-server --appendonly yes
    restart: always
      
  database:
    image: "postgress:latest"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: "coursdevops"
      POSTGRES_USER: "eve"
      POSTGRES_PASSWORD: "azerty"
    volumes: 
    - "cours:/var/lib/postgresql/data"
    ports:
    - "5432:5432"

volumes:
  dbsql:
  dbredis:
