version: "3.1"

services: 
  database:
    image: "postgress:latest"
    restart: "unless-stopped"
    environnement:
      POSTGRES_DB: "coursdevops"
      POSTGRES_USER: "eve"
      POSTGRES_PASSWORD: "azerty"
    volumes: 
    - "cours:/var/lib/postgresql/data"
    ports:
    - "5432:5432"

volumes:
  cours:
